Repository gdalle/SparseMatrixColorings.jl, pull requests merged in 2025-03, with the labels that each got.

#197 Optimize remap_colors
  src/coloring.jl
  src/decompression.jl
  src/result.jl
Labels: benchmark

#200 Implement fast coloring without decompression prep
  docs/src/api.md
  src/SparseMatrixColorings.jl
  src/interface.jl
  test/small.jl
  test/utils.jl
Labels: benchmark

#205 Improve decompress_single_color! for StarSetColoringResult
  src/decompression.jl
Labels: performance

#180 Detect stars in the forest for acyclic coloring
  src/coloring.jl
  src/decompression.jl
  test/allocations.jl
Labels: benchmark

#190 Implement our own structure Forest
  Project.toml
  docs/src/dev.md
  src/SparseMatrixColorings.jl
  src/coloring.jl
  src/forest.jl
  test/forest.jl
  test/runtests.jl
Labels: performance, benchmark
