Repository gdalle/SparseMatrixColorings.jl, pull requests merged in 2025-02, with the labels that each got.

#176 Reduce the dynamic allocations in acyclic coloring
  src/coloring.jl
Labels: benchmark

#187 Improve benchmarks, add bicoloring
  .github/workflows/Benchmark.yml
  benchmark/benchmarks.jl
Labels: benchmark

#191 Update show_colors.jl
  src/show_colors.jl
Labels: documentation

#186 Add an attribute has_loops in AdjacencyGraph
  src/coloring.jl
  src/decompression.jl
  src/graph.jl
  src/interface.jl
  src/result.jl
Labels: benchmark

#179 Remove vertices_by_tree for the acyclic coloring
  src/coloring.jl
  src/decompression.jl
  src/result.jl
Labels: benchmark

#156 Improve how we build A_and_Aᵀ
  docs/src/dev.md
  src/graph.jl
  src/interface.jl
  test/graph.jl
Labels: performance
