Repository gdalle/SparseMatrixColorings.jl, pull requests merged in 2025-04, with the labels that each got.

#228 Improve the computation of TreeSet
  src/coloring.jl
  src/decompression.jl
  src/result.jl
Labels: performance

#233 Remove the dictionaries in TreeSet
  src/coloring.jl
  src/decompression.jl
  src/forest.jl
  test/allocations.jl
Labels: performance, benchmark

#245 Update how we use visited_trees in TreeSet
  src/coloring.jl
Labels: benchmark

#244 More efficient reset of visited vertices in order.jl
  src/order.jl
Labels: benchmark

#248 Remove some useless operations in dynamic orders
  src/order.jl
  test/order.jl
Labels: benchmark
